# Generated by Django 5.1.1 on 2024-10-24 13:27

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bolsista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=255)),
                ('matricula', models.CharField(default='', max_length=12)),
                ('curso', models.CharField(default='', max_length=100)),
                ('grauEscolar', models.CharField(default='', max_length=255)),
                ('tipoDeBolsa', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diaSemana', models.CharField(default='', max_length=255)),
                ('horarioInicio', models.CharField(default='', max_length=255)),
                ('horarioFim', models.TimeField(default='', max_length=255)),
                ('bolsista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bolsista_horario', to='manager.bolsista')),
            ],
        ),
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=datetime.datetime(2024, 10, 24, 13, 27, 17, 707121, tzinfo=datetime.timezone.utc))),
                ('horaEntrada', models.DateTimeField(default=datetime.datetime(2024, 10, 24, 13, 27, 17, 770521, tzinfo=datetime.timezone.utc))),
                ('horaSaida', models.DateTimeField(default='')),
                ('bolsista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bolsista_presenca', to='manager.bolsista')),
            ],
        ),
    ]
