# Generated by Django 5.1.1 on 2025-01-27 19:15

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bolsista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(default='', max_length=12)),
                ('cpf', models.CharField(default='', max_length=14)),
                ('curso', models.CharField(default='', max_length=255)),
                ('grauEscolar', models.CharField(default='', max_length=255)),
                ('tipoDeBolsa', models.CharField(default='', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_bolsista', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diaSemana', models.CharField(default='', max_length=255)),
                ('horarioInicio', models.CharField(default='', max_length=255)),
                ('horarioFim', models.TimeField(default='', max_length=255)),
                ('bolsista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bolsista_horario', to='manager.bolsista')),
            ],
        ),
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=datetime.datetime(2025, 1, 27, 19, 15, 24, 42683, tzinfo=datetime.timezone.utc))),
                ('horaEntrada', models.DateTimeField(default=datetime.datetime(2025, 1, 27, 19, 15, 24, 89553, tzinfo=datetime.timezone.utc))),
                ('horaSaida', models.DateTimeField(default='')),
                ('bolsista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bolsista_presenca', to='manager.bolsista')),
            ],
        ),
    ]
