# Generated by Django 5.1.1 on 2025-01-27 19:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_alter_presenca_data_alter_presenca_horaentrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolsista',
            name='grauEscolar',
            field=models.CharField(choices=[('TIM', 'Técnico Integrado ao Médio'), ('TS', 'Técnico Subsequente'), ('ES', 'Ensino Superior'), ('PG', 'Pós-Graduação'), ('DT', 'Doutorado')], default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='bolsista',
            name='tipoDeBolsa',
            field=models.CharField(choices=[('VLT', 'Voluntária - 10h'), ('RMN1', 'Remunerada - 12h a 20h'), ('RMN2', 'Remunerada - 30h')], default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='presenca',
            name='data',
            field=models.DateField(default=datetime.datetime(2025, 1, 27, 19, 35, 40, 461074, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='presenca',
            name='horaEntrada',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 19, 35, 40, 523560, tzinfo=datetime.timezone.utc)),
        ),
    ]
