# Generated by Django 5.1.1 on 2025-01-28 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_alter_bolsista_grauescolar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presenca',
            name='data',
            field=models.DateField(default=datetime.datetime(2025, 1, 28, 17, 59, 38, 244559, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='presenca',
            name='horaEntrada',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 17, 59, 38, 302753, tzinfo=datetime.timezone.utc)),
        ),
    ]
