# Generated by Django 5.1.1 on 2025-01-31 17:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_alter_presenca_data_alter_presenca_horaentrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolsista',
            name='grauEscolar',
            field=models.CharField(choices=[('', 'Selecionar'), ('TIM', 'Técnico Integrado ao Médio'), ('TS', 'Técnico Subsequente'), ('ES', 'Ensino Superior'), ('PG', 'Pós-Graduação'), ('DT', 'Doutorado')], default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='bolsista',
            name='tipoDeBolsa',
            field=models.CharField(choices=[('', 'Selecionar'), ('VLT', 'Voluntária - 10h'), ('RMN1', 'Remunerada - 12h a 20h'), ('RMN2', 'Remunerada - 30h')], default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='horario',
            name='diaSemana',
            field=models.CharField(choices=[('', 'Selecionar'), ('seg', 'Segunda'), ('ter', 'Terça'), ('qua', 'Quarta'), ('qui', 'Quinta'), ('sex', 'Sexta'), ('sab', 'Sábado')], default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='horario',
            name='horarioFim',
            field=models.CharField(choices=[('', 'Selecionar'), ('m1', 'M1: 7:00 - 7:50'), ('m2', 'M2: 7:50 - 8:40'), ('m3', 'M3: 8:50 - 9:40'), ('m4', 'M4: 9:40 - 10:30'), ('m5', 'M5: 10:40 - 11:30'), ('m6', 'M6: 11:30 - 12:20'), ('am', 'AM: 12:00 - 12:50'), ('t1', 'T1: 13:00 - 13:50'), ('t2', 'T2: 13:50 - 14:40'), ('t3', 'T3: 14:50 - 15:40'), ('t4', 'T4: 15:40 - 16:30'), ('t5', 'T5: 16:40 - 17:30'), ('t6', 'T6: 17:30 - 18:20'), ('n1', 'N1: 18:40 - 19:30'), ('n2', 'N2: 19:30 - 20:20'), ('n3', 'N3: 20:30 - 21:20'), ('n4', 'N4: 21:20 - 22:10')], default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='horario',
            name='horarioInicio',
            field=models.CharField(choices=[('', 'Selecionar'), ('m1', 'M1: 7:00 - 7:50'), ('m2', 'M2: 7:50 - 8:40'), ('m3', 'M3: 8:50 - 9:40'), ('m4', 'M4: 9:40 - 10:30'), ('m5', 'M5: 10:40 - 11:30'), ('m6', 'M6: 11:30 - 12:20'), ('am', 'AM: 12:00 - 12:50'), ('t1', 'T1: 13:00 - 13:50'), ('t2', 'T2: 13:50 - 14:40'), ('t3', 'T3: 14:50 - 15:40'), ('t4', 'T4: 15:40 - 16:30'), ('t5', 'T5: 16:40 - 17:30'), ('t6', 'T6: 17:30 - 18:20'), ('n1', 'N1: 18:40 - 19:30'), ('n2', 'N2: 19:30 - 20:20'), ('n3', 'N3: 20:30 - 21:20'), ('n4', 'N4: 21:20 - 22:10')], default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='presenca',
            name='data',
            field=models.DateField(default=datetime.datetime(2025, 1, 31, 17, 48, 37, 523076, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='presenca',
            name='horaEntrada',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 31, 17, 48, 37, 569946, tzinfo=datetime.timezone.utc)),
        ),
    ]
