# Generated by Django 5.1.1 on 2025-04-10 23:00

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_alter_bolsista_grauescolar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=255)),
                ('departamento', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='bolsista',
            name='laboratorio',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='presenca',
            name='data',
            field=models.DateField(default=datetime.datetime(2025, 4, 10, 23, 0, 11, 440196, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='presenca',
            name='horaEntrada',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 10, 23, 0, 11, 502708, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='HorarioBolsista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diaSemana', models.CharField(choices=[('', 'Selecionar'), ('Segunda', 'Segunda'), ('Terça', 'Terça'), ('Quarta', 'Quarta'), ('Quinta', 'Quinta'), ('Sexta', 'Sexta'), ('Sábado', 'Sábado')], default='', max_length=255)),
                ('horarioInicio', models.CharField(choices=[('', 'Selecionar'), ('M1: 7:00 - 7:50', 'M1: 7:00 - 7:50'), ('M2: 7:50 - 8:40', 'M2: 7:50 - 8:40'), ('M3: 8:50 - 9:40', 'M3: 8:50 - 9:40'), ('M4: 9:40 - 10:30', 'M4: 9:40 - 10:30'), ('M5: 10:40 - 11:30', 'M5: 10:40 - 11:30'), ('M6: 11:30 - 12:20', 'M6: 11:30 - 12:20'), ('Almoço: 12:00 - 12:50', 'Almoço: 12:00 - 12:50'), ('T1: 13:00 - 13:50', 'T1: 13:00 - 13:50'), ('T2: 13:50 - 14:40', 'T2: 13:50 - 14:40'), ('T3: 14:50 - 15:40', 'T3: 14:50 - 15:40'), ('T4: 15:40 - 16:30', 'T4: 15:40 - 16:30'), ('T5: 16:40 - 17:30', 'T5: 16:40 - 17:30'), ('T6: 17:30 - 18:20', 'T6: 17:30 - 18:20'), ('N1: 18:40 - 19:30', 'N1: 18:40 - 19:30'), ('N2: 19:30 - 20:20', 'N2: 19:30 - 20:20'), ('N3: 20:30 - 21:20', 'N3: 20:30 - 21:20'), ('N4: 21:20 - 22:10', 'N4: 21:20 - 22:10')], default='', max_length=255)),
                ('horarioFim', models.CharField(choices=[('', 'Selecionar'), ('M1: 7:00 - 7:50', 'M1: 7:00 - 7:50'), ('M2: 7:50 - 8:40', 'M2: 7:50 - 8:40'), ('M3: 8:50 - 9:40', 'M3: 8:50 - 9:40'), ('M4: 9:40 - 10:30', 'M4: 9:40 - 10:30'), ('M5: 10:40 - 11:30', 'M5: 10:40 - 11:30'), ('M6: 11:30 - 12:20', 'M6: 11:30 - 12:20'), ('Almoço: 12:00 - 12:50', 'Almoço: 12:00 - 12:50'), ('T1: 13:00 - 13:50', 'T1: 13:00 - 13:50'), ('T2: 13:50 - 14:40', 'T2: 13:50 - 14:40'), ('T3: 14:50 - 15:40', 'T3: 14:50 - 15:40'), ('T4: 15:40 - 16:30', 'T4: 15:40 - 16:30'), ('T5: 16:40 - 17:30', 'T5: 16:40 - 17:30'), ('T6: 17:30 - 18:20', 'T6: 17:30 - 18:20'), ('N1: 18:40 - 19:30', 'N1: 18:40 - 19:30'), ('N2: 19:30 - 20:20', 'N2: 19:30 - 20:20'), ('N3: 20:30 - 21:20', 'N3: 20:30 - 21:20'), ('N4: 21:20 - 22:10', 'N4: 21:20 - 22:10')], default='', max_length=255)),
                ('bolsista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bolsista_horario', to='manager.bolsista')),
            ],
        ),
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=255)),
                ('localizacao', models.CharField(default='', max_length=500)),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laboratorios', to='manager.setor')),
            ],
        ),
        migrations.DeleteModel(
            name='Horario',
        ),
    ]
